### ISSUE TITLE
animefire.net

### ISSUE THREAD

**Issue by animetrom** [bogachenko/fuckfuckadblock#230] opened 2021-10-15 04:11 UTC
### Basic information

**Check the link:** `https://animefire.net/animes/sekai-saikou-no-ansatsusha-isekai-kizoku-ni-tensei-suru/2`
**Category:** Anti-adblock

### User environment

**Browser:** Chrome 94.0
**Extension or program:** AdGuard (Program)
**DNS:** No use.
**Extensions:** Yes, tampermonkey, darkreader

### Additional message

please disabe adblock killer.

**Comment by bogachenko** [comment] 2021-10-15 08:56
Duplicate of #212

**Closed by bogachenko** 2021-10-15 08:56 UTC
Labels: duplicate, antiadblock, geolock
