### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by runboy93** [bogachenko/fuckfuckadblock#244] opened 2021-11-24 19:47 UTC
### Basic information

**Check the link:** `https://myanimelist.net`
**Category:**
**Reported from:** Finland

### User environment

**Browser:** Vivaldi 4.3 (Android)
**Extension or program:** Vivaldi adblock
**DNS:**
**Extensions:**

### Additional message

This seems to be problem with mobiles devices only (Android, iOS), basically this happens:
https://www.reddit.com/r/MyAnimeList/comments/r08lnn/anyone_know_how_to_fix_this_cant_click_anything/

When you open website on mobile device and with mobile browser (Chrome, Vivaldi, Safari...), after waiting for while whole screen be grayed out and can't tap anything on website.

Not sure if this is antiadblock, cookie policy prompt or what but it is very annoing.

Noticed this host on mobile website, which is not on desktop website: "**smartadserver.com**", I hope this information helps even little.

**Comment by bogachenko** [comment] 2021-11-26 12:06
Duplicate of #243

**Closed by bogachenko** 2021-11-26 12:06 UTC
