### ISSUE TITLE
devuploads.com

### ISSUE THREAD

**Issue by animetrom** [bogachenko/fuckfuckadblock#428] opened 2023-05-24 00:52 UTC
### Basic information

**Check the link:** `https://devuploads.com/xuueb8fsj3ji`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** Firefox 113.0.1
**Adblocker:** uBlock Origin 1.49.2
**Extensions:** Tampermonkey
**DNS:** None

**Comment by bogachenko** [comment] 2023-05-24 02:52
Hi, I can't reproduce your issue.
Are you trying to go to the site with default settings + Fuck Fuckadblock for uBO?

>Extensions: Tampermonkey

https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions

**Comment by bogachenko** [comment] 2023-05-24 04:52
Does it work for you @animetrom ?
```
@@||securepubads.g.doubleclick.net/tag/js/gpt.js|$script,third-party
@@||securepubads.g.doubleclick.net/pagead/ppub_config?$xmlhttprequest,third-party
@@||securepubads.g.doubleclick.net/pagead/*/pubads_impl.js|$script,third-party
*$subdocument,domain=thecubexguide.com|devuploads.com|miuiflash.com|djxmaza.in,redirect=noopframe
@@*$generichide,domain=thecubexguide.com|devuploads.com|miuiflash.com|djxmaza.in
@@||tpc.googlesyndication.com/sodar/sodar2.js|$script
@@||pagead2.googlesyndication.com^$xmlhttprequest,domain=thecubexguide.com|devuploads.com|miuiflash.com|djxmaza.in
```

**Comment by animetrom** [comment] 2023-05-24 20:50
Unfortunately it remains the same.  Still preventing me from being able to download the files.

**Comment by bogachenko** [comment] 2023-05-25 02:12
Hi, you can try to temporarily turn off all the lists in your uBO, leaving only `Easylist`, `Easylist Privacy` and `Fuck Fuckadblock`?
Please clean your data in your browser using the "Browser Cleaning Wizard", on Firefox it is launched by the <kbd>Shift</kbd> + <kbd>Ctrl</kbd> + <kbd>Del</kbd> key combination, select the "Everywhere" method in Time rage to clean and mark all the boxes in the "History" section, and click the big blue "Clear Now" button.
Then go to the website and try to reproduce the issue.

**Comment by animetrom** [comment] 2023-05-25 02:33
It persists just the same.

https://i.imgur.com/xixN1EJ.png

**Comment by bogachenko** [comment] 2023-05-25 03:17
It's funny, but I can't reproduce it with such settings, with uBO filters, this notification appears 1-2 times, but disappears after the page refresh.

What do you have installed in Tampermonkey ? Are there definitely no other extensions? File hosts.txt empty?  Do you have an antivirus?

**Comment by animetrom** [comment] 2023-05-25 03:24
I deactivate all extensions, I only used the filters you gave me and nothing.
Neither switching browsers, nor using the cell phone. Everything holds.

**Comment by biden2020prez** [comment] 2023-06-29 03:43
I am also having issues on devuploads.com

**Comment by nightznero** [comment] 2023-11-08 19:15
me either sometime have issue with this site. This ad train site is sesitive for any adblockers. 'Devuploads.com' own sites like; 'dev.miuiflash.com' 'djxmaza.in' 'mayaremix.in' *not sure* 'thecubexguide.com'

**Comment by bogachenko** [comment] 2024-07-13 15:51
Fixed in uBO - Ads sheet.

**Closed** 2024-07-13 15:50 UTC
Labels: antiadblock, geolock
