### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by FahadBinHussain** [bogachenko/fuckfuckadblock#418] opened 2023-04-27 16:20 UTC
### Basic information

**Check the link:** `https://dropgalaxy.com/drive/pzx0r1zlf99r`
**Category:** Anti-adblock
**Reported from:** Bangladesh 

### User environment

**Browser:** Edge 112.0.1722.46 (Android) 
**Adblocker:** AdGuard for Android v4.0 Nightly 78 
**Extensions:** None 
**DNS:** None 

### Additional message

Adblock Detected message, when downloading anything from this site

**Comment by bogachenko** [comment] 2023-04-29 00:00
Can’t reproduce your the issue.

Please answer a couple of questions:
1. Does your phone have root rights?
2. Have you tried to access the site through another browser?
3. You indicated that you do not use DNS, does this mean that you have "System DNS" in the settings of AdGuard?

**Comment by FahadBinHussain** [comment] 2023-04-29 00:41
1. Yes, my phone has root rights
2. No, I haven't tried to access the site through another browser
3. I have Automatic DNS selected in AdGuard. I didn't change anything related to DNS anywhere in my system or AdGuard. So, it should be default everywhere.

**Comment by bogachenko** [comment] 2023-04-29 03:15
>No, I haven't tried to access the site through another browser

Have you disabled the built-in ad blocker in the Edge browser?

>I have Automatic DNS selected in AdGuard. I didn't change anything related to DNS anywhere in my system or AdGuard. So, it should be default everywhere.

Do you have [the list](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt) of filters from AdGuard for blocking DNS queries enabled?

**Comment by bogachenko** [comment] 2023-04-29 03:18
Duplicate of https://github.com/bogachenko/fuckfuckadblock/issues/79

**Comment by FahadBinHussain** [comment] 2023-04-29 07:01
1. After disabling the built-in Edge Android Adblocker, the Adblock Detected message doesn't show.
2. Did you mean this?

![Screenshot_2023-04-29-13-00-11-111_com adguard android](https://user-images.githubusercontent.com/75292632/235288711-b9e0f0f2-9f15-402e-ab79-2fe304d43c68.png)

**Closed** 2023-04-29 09:31 UTC
Labels: duplicate, antiadblock, unable to reproduce

**Comment by bogachenko** [comment] 2023-04-29 09:50
>After disabling the built-in Edge Android Adblocker, the Adblock Detected message doesn't show.

I wrote about the use of 2 blockers in [this article](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#before-sending-a-report), which you should have read before sending a report. It was in the markup of the report template, but you didn't read it.

> Did you mean this AdGuard DNS Filter (Optimized)?

Yes, I'm talking about it.  This can also be one of the reasons for false positives on pages.  I used your example to describe the experience of [using local server filtering](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy/_compare/8c029f4a9cb5e70678bb40653a94151679f2d190...de8f87b320b7acb66dc009fb16e63da85a54ad90).

**please don't upload an image here, this was also mentioned in the report writing article.**

**Comment by FahadBinHussain** [comment] 2023-04-29 10:17
1. Yes, I didn't read that, somehow missed.
2. I turned off DNS protection altogether in Adguard but still the same 'Adblock detected' message

**Comment by bogachenko** [comment] 2023-04-29 10:40
>Atfirst, I turned off Adguard DNS Filter (Optimized). But still the same 'Adblock detected' message. Then, I turned off DNS protection altogether in Adguard but still the same issue.

I wrote that this may be one of the reasons for the false positive, and not that this is the reason.

**Comment by FahadBinHussain** [comment] 2023-04-29 11:02
Yeah, I understood. Just wanted to let you know that turning that off doesn't work too.
