### ISSUE TITLE
tii.la

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#400] opened 2023-03-20 17:24 UTC
### Basic information

**Check the link:**  `https://tii.la/8fIjORyg`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Latest Chrome
**Adblocker:**  Latest Ublock Origin
**Extensions:**  -
**DNS:**  -

**Comment by bogachenko** [comment] 2023-03-21 01:08
Duplicate of #167

**Closed** 2023-03-21 01:08 UTC
Labels: antiadblock
