### ISSUE TITLE
flightsim.to

### ISSUE THREAD

**Issue by jshir** [bogachenko/fuckfuckadblock#406] opened 2023-03-27 18:04 UTC
### Basic information

**Check the link:** `https://flightsim.to/file/52114/lpsc-aerodromo-de-santa-cruz`
**Category:** Anti-adblock
**Reported from:** Mullvad VPN Chicago IL

### User environment

**Browser:** Firefox 111.0.1
**Adblocker:** uBO 1.48.1b4
**Extensions:** Violentmonkey but it is turned off now
**DNS:** N/A

### Additional message

Downloads above a certain size show the disable adblock message after the download countdown.
FFAB actually got rid of this message successfully until today, they worked around it.

**Comment by bogachenko** [comment] 2023-03-28 01:35
Hi I can't reproduce. Tell me your VPN does not change DNS, can you try without it?
This is happening in all browsers, can you check not on Firefox?

Go to the uBO settings in the "Support" tab, find the field "Troubleshooting" below and send here.

**Comment by jshir** [comment] 2023-03-28 02:13
At this moment I cannot either. I think they're A/B testing. I'll try to save the page and troubleshooting info if/when it comes back.

**Comment by bogachenko** [comment] 2023-03-28 02:22
I'll close it for now, write here how and what - I'll open it.

**Comment by jshir** [comment] 2023-05-10 15:19
Hi there, it's back. You can see it at https://flightsim.to/file/19345/msfs-2020-google-map-replacement without need for an account, just hit download.

**Comment by jshir** [comment] 2023-05-10 15:54
I was able to find the AAB and create a filter that solves it.

flightsim.to##+js(set-constant.js, checkAdsBlocked, noopFunc)

**Comment by bogachenko** [comment] 2023-05-12 13:22
>user-filters: 44-0, never

**Comment by bogachenko** [comment] 2023-05-12 14:14
>lol I still can't reproduce it. Can you test on another browser, you have changed settings in uBO, in Firefox (and its extensions) for sure too and check out the rest of the steps I've described here?

**Comment by jshir** [comment] 2023-05-12 14:26
Clean chrome with clean uBO reproduced.

uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94380
 cosmetic: 38825
 scriptlet: 17424
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65607-46, now
  easyprivacy: 32261-46, now
  plowe-0: 3737-937, now
  ublock-abuse: 70-0, now
  ublock-badware: 7120-128, now
  ublock-filters: 33102-95, now
  ublock-privacy: 394-74, now
  ublock-quick-fixes: 252-12, now
  ublock-unbreak: 2012-40, now
  urlhaus-1: 7605-1, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 639 ms
 maxAssetCacheWait: 49 ms


Also with FFAB

uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 98244
 cosmetic: 39382
 scriptlet: 34665
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24157-12, now
 default: 
  user-filters: 0-0, never
  easylist: 65607-51, 1m
  easyprivacy: 32261-46, 1m
  plowe-0: 3737-937, 1m
  ublock-abuse: 70-1, 1m
  ublock-badware: 7120-128, 1m
  ublock-filters: 33102-2571, 1m
  ublock-privacy: 394-74, 1m
  ublock-quick-fixes: 252-12, 1m
  ublock-unbreak: 2012-41, 1m
  urlhaus-1: 7605-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 261 ms
 maxAssetCacheWait: 102 ms

**Comment by jshir** [comment] 2023-05-12 14:30
They are disabling AAB geographically in some areas. I connected to a VPN in Serbia and it went away. Try a USA VPN.

**Closed** 2023-05-13 00:14 UTC
Labels: antiadblock, geolock, need account
